# Generated by Django 4.0.2 on 2022-02-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karamel', '0003_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='profiles')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karamel.userinfo')),
            ],
        ),
    ]
