# Generated by Django 4.0.2 on 2022-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
